<?php
/* -----------------------------------------------------------------------------------------
   Automated Translated by Reqser.com using Modified Modul Version 2.5 on the 25.01.2024
   ---------------------------------------------------------------------------------------*/


/***********************************************************
* file: translations_deepl.php
* path: /lang/greek/modules/system/
* use: language file for system module
*
* © copyright 07-2023, noRiddle
             ____
            |    |       |     | |
  __   ___  |____/ °  ___|  ___| |  ___
|/  | |   | |   \  | |   | |   | | |___|
|   n |___o |    R i |___d |__ d l |__e

* © copyright JorisK Reqser.com 08-2023

***********************************************************/
define('MODULE_SYSTEM_REQSER_TITLE', '&Alpha;&upsilon;&tau;ό&mu;&alpha;&tau;&epsilon;&sigmaf; &mu;&epsilon;&tau;&alpha;&phi;&rho;ά&sigma;&epsilon;&iota;&sigmaf; DeepL &mu;έ&sigma;&omega; <i>&tau;&omicron;&upsilon;</i> Reqser <i>.com</i>, έ&kappa;&delta;&omicron;&sigma;&eta; &mu;&omicron;&nu;ά&delta;&alpha;&sigmaf; %s<br />- build for <i>Reqser</i>.com -<br />&copy; <a href="http://www.revilonetz.de/kontakt" target="_blank" title="Kontaktiere noRiddle" style="color:#02afc3;">noRiddle</a> &kappa;&alpha;&iota; &copy; <a href="https://www.reqser.com" target="_blank" title="Kontaktiere Reqser" style="color:#02afc3;">Reqser.com</a> (07-2023 - ' . date('m-Y') . ')');
define('MODULE_SYSTEM_REQSER_DESCRIPTION', '
<a href="https://www.reqser.com" target="_blank"><img src="images/reqser_modul/modul_logo.png" border=0 width="400px"></a></br> &Epsilon;&nu;ό&tau;&eta;&tau;&alpha; &sigma;&upsilon;&sigma;&tau;ή&mu;&alpha;&tau;&omicron;&sigmaf; &gamma;&iota;&alpha; &tau;&eta;&nu; &epsilon;&nu;&epsilon;&rho;&gamma;&omicron;&pi;&omicron;ί&eta;&sigma;&eta; &kappa;&alpha;&iota; &tau;&eta; &delta;&iota;&alpha;&mu;ό&rho;&phi;&omega;&sigma;&eta; &mu;&epsilon;&tau;&alpha;&phi;&rho;ά&sigma;&epsilon;&omega;&nu; &mu;έ&sigma;&omega; <i><a href="https://reqser.com/" target="_blank">reqser.com</i></a>');
define('MODULE_SYSTEM_REQSER_STATUS_TITLE', '<h2>&Beta;&alpha;&sigma;&iota;&kappa;έ&sigmaf; &rho;&upsilon;&theta;&mu;ί&sigma;&epsilon;&iota;&sigmaf;</h2>&Epsilon;&nu;&epsilon;&rho;&gamma;&omicron;&pi;&omicron;ί&eta;&sigma;&eta; &mu;&omicron;&nu;ά&delta;&alpha;&sigmaf;?');
define('MODULE_SYSTEM_REQSER_STATUS_DESC', '');
define('MODULE_SYSTEM_REQSER_REQSER_API_KEY_TITLE', '&Kappa;&lambda;&epsilon;&iota;&delta;ί API Reqser');
define('MODULE_SYSTEM_REQSER_REQSER_API_KEY_DESC', '&Mu;&pi;&omicron;&rho;&epsilon;ί&tau;&epsilon; &nu;&alpha; &epsilon;&iota;&sigma;&alpha;&gamma;ά&gamma;&epsilon;&tau;&epsilon; &tau;&omicron; &kappa;&lambda;&epsilon;&iota;&delta;ί API &alpha;&pi;ό <i>&tau;&omicron; Reqser.</i> com &epsilon;&delta;ώ. &Epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&epsilon;&tau;&alpha;&iota; &kappa;&alpha;&tau;ά &tau;&eta; &sigma;ύ&nu;&delta;&epsilon;&sigma;&eta; &mu;&epsilon; &tau;&omicron; Modified &sigma;&tau;&omicron; Reqser. <a href="https://www.reqser.com/translation/new-website/Modified" target="_blank" title="Direkt Link">&amp;raquo &Alpha;&pi;&epsilon;&upsilon;&theta;&epsilon;ί&alpha;&sigmaf; &sigma;ύ&nu;&delta;&epsilon;&sigma;&eta; &epsilon;&delta;ώ</a> ');
define('MODULE_SYSTEM_REQSER_TEMP_SHOP_TOKEN_TITLE', '&Pi;&rho;&omicron;&sigma;&omega;&rho;&iota;&nu;ό &delta;&iota;&alpha;&kappa;&rho;&iota;&tau;&iota;&kappa;ό &alpha;&sigma;&phi;&alpha;&lambda;&epsilon;ί&alpha;&sigmaf;');
define('MODULE_SYSTEM_REQSER_TEMP_SHOP_TOKEN_DESC', '&Pi;&rho;&omicron;&sigma;&omega;&rho;&iota;&nu;ό &delta;&iota;&alpha;&kappa;&rho;&iota;&tau;&iota;&kappa;ό &alpha;&sigma;&phi;&alpha;&lambda;&epsilon;ί&alpha;&sigmaf; &gamma;&iota;&alpha; &epsilon;&xi;&omega;&tau;&epsilon;&rho;&iota;&kappa;ά &epsilon;&rho;&omega;&tau;ή&mu;&alpha;&tau;&alpha; &sigma;&tau;&omicron; &kappa;&alpha;&tau;ά&sigma;&tau;&eta;&mu;&alpha;.<br /><span  class="alrt">&Alpha;&pi;&omicron;&delta;ί&delta;&epsilon;&tau;&alpha;&iota; &alpha;&upsilon;&tau;ό&mu;&alpha;&tau;&alpha; !</span>');
define('MODULE_SYSTEM_REQSER_TST_VALID_UNTIL_TITLE', '&Iota;&sigma;&chi;ύ&sigmaf; &tau;&omicron;&upsilon; &pi;&rho;&omicron;&sigma;&omega;&rho;&iota;&nu;&omicron;ύ &sigma;&upsilon;&mu;&beta;ό&lambda;&omicron;&upsilon; &alpha;&sigma;&phi;&alpha;&lambda;&epsilon;ί&alpha;&sigmaf;');
define('MODULE_SYSTEM_REQSER_TST_VALID_UNTIL_DESC', '&Tau;&omicron; &pi;&rho;&omicron;&sigma;&omega;&rho;&iota;&nu;ό &delta;&iota;&alpha;&kappa;&rho;&iota;&tau;&iota;&kappa;ό &alpha;&sigma;&phi;&alpha;&lambda;&epsilon;ί&alpha;&sigmaf; &iota;&sigma;&chi;ύ&epsilon;&iota; &mu;έ&chi;&rho;&iota; (&beta;&lambda;. &pi;&alpha;&rho;&alpha;&kappa;ά&tau;&omega;).<br />Ό&tau;&alpha;&nu; &lambda;ή&xi;&epsilon;&iota;, έ&nu;&alpha; &nu;έ&omicron; &theta;&alpha; &delta;&eta;&mu;&iota;&omicron;&upsilon;&rho;&gamma;&eta;&theta;&epsilon;ί &kappa;&alpha;&tau;ό&pi;&iota;&nu; &alpha;&iota;&tau;ή&mu;&alpha;&tau;&omicron;&sigmaf; &alpha;&pi;ό &epsilon;&xi;&omega;&tau;&epsilon;&rho;&iota;&kappa;ή &pi;&eta;&gamma;ή &kappa;&alpha;&iota; &sigma;&tau;&eta; &sigma;&upsilon;&nu;έ&chi;&epsilon;&iota;&alpha; &theta;&alpha; &epsilon;&mu;&phi;&alpha;&nu;ί&zeta;&epsilon;&tau;&alpha;&iota; &epsilon;&delta;ώ.');
define('MODULE_SYSTEM_REQSER_ALLOW_ALL_ROW_ACCESS_TITLE', '<hr /><h2>&Pi;ί&nu;&alpha;&kappa;&epsilon;&sigmaf; &gamma;&lambda;&omega;&sigma;&sigma;ώ&nu;</h2>&Delta;ώ&sigma;&tau;&epsilon; &sigma;&tau;&omicron; Reqser.com &pi;&rho;ό&sigma;&beta;&alpha;&sigma;&eta; &sigma;&epsilon; ό&lambda;&epsilon;&sigmaf; &tau;&iota;&sigmaf; &sigma;&tau;ή&lambda;&epsilon;&sigmaf; &tau;&omicron;&upsilon; &kappa;&omicron;&iota;&nu;&omicron;ύ &pi;ί&nu;&alpha;&kappa;&alpha; ?');
define('MODULE_SYSTEM_REQSER_ALLOW_ALL_ROW_ACCESS_DESC', '&Tau;&omicron; "&Nu;&alpha;&iota;" &delta;ί&nu;&epsilon;&iota; &sigma;&tau;&omicron; Reqser &pi;&rho;ό&sigma;&beta;&alpha;&sigma;&eta; &sigma;&epsilon; ό&lambda;&epsilon;&sigmaf; &tau;&iota;&sigmaf; &kappa;&alpha;&tau;&alpha;&chi;&omega;&rho;ή&sigma;&epsilon;&iota;&sigmaf; &sigma;&tau;&eta;&lambda;ώ&nu; &tau;&omega;&nu; &alpha;&pi;&omicron;&delta;&epsilon;&sigma;&mu;&epsilon;&upsilon;&mu;έ&nu;&omega;&nu; &pi;&iota;&nu;ά&kappa;&omega;&nu;, &epsilon;&nu;ώ &tau;&omicron; "Ό&chi;&iota;" &mu;&pi;&omicron;&rho;&epsilon;ί &nu;&alpha; &omicron;&delta;&eta;&gamma;ή&sigma;&epsilon;&iota; &sigma;&epsilon; &sigma;&phi;ά&lambda;&mu;&alpha;&tau;&alpha; &mu;&epsilon; &pi;&alpha;&lambda;&iota;έ&sigmaf; &epsilon;&kappa;&delta;ό&sigma;&epsilon;&iota;&sigmaf; &kappa;&alpha;&tau;&alpha;&sigma;&tau;&eta;&mu;ά&tau;&omega;&nu; ή &kappa;&alpha;&tau;ά &tau;&eta; &chi;&rho;ή&sigma;&eta; &mu;&eta; &tau;&upsilon;&pi;&omicron;&pi;&omicron;&iota;&eta;&mu;έ&nu;&omega;&nu; &pi;&rho;&omicron;&tau;ύ&pi;&omega;&nu;.');
define('MODULE_SYSTEM_REQSER_TABLES_TO_TRANSL_TITLE', '&Pi;ί&nu;&alpha;&kappa;&epsilon;&sigmaf; &beta;ά&sigma;&eta;&sigmaf; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu;');
define('MODULE_SYSTEM_REQSER_TABLES_TO_TRANSL_DESC', '&Tau;&upsilon;&pi;&omicron;&pi;&omicron;&iota;&eta;&mu;έ&nu;&omicron;&iota; &pi;ί&nu;&alpha;&kappa;&epsilon;&sigmaf; &beta;ά&sigma;&eta;&sigmaf; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu; &pi;&rho;&omicron;&sigmaf; &mu;&epsilon;&tau;ά&phi;&rho;&alpha;&sigma;&eta;.');
define('MODULE_SYSTEM_REQSER_MORE_TABLES_TITLE', '&Pi;&epsilon;&rho;&alpha;&iota;&tau;έ&rho;&omega; &pi;ί&nu;&alpha;&kappa;&epsilon;&sigmaf; &tau;&eta;&sigmaf; &beta;ά&sigma;&eta;&sigmaf; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu;');
define('MODULE_SYSTEM_REQSER_MORE_TABLES_DESC', '&Epsilon;&pi;&iota;&lambda;έ&xi;&tau;&epsilon; &pi;&epsilon;&rho;&alpha;&iota;&tau;έ&rho;&omega; &pi;ί&nu;&alpha;&kappa;&epsilon;&sigmaf; &beta;ά&sigma;&eta;&sigmaf; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu; &pi;&rho;&omicron;&sigmaf; &mu;&epsilon;&tau;ά&phi;&rho;&alpha;&sigma;&eta; &epsilon;&delta;ώ');
define('MODULE_SYSTEM_REQSER_MORE_TABLES_ADD_TITLE', 'Ά&lambda;&lambda;&omicron;&iota; &pi;ί&nu;&alpha;&kappa;&epsilon;&sigmaf; &tau;&eta;&sigmaf; &beta;ά&sigma;&eta;&sigmaf; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu; (&delta;&epsilon;&nu; &epsilon;ί&nu;&alpha;&iota; &delta;&iota;&alpha;&theta;έ&sigma;&iota;&mu;&omicron;&iota; &gamma;&iota;&alpha; &epsilon;&pi;&iota;&lambda;&omicron;&gamma;ή &pi;&alpha;&rho;&alpha;&pi;ά&nu;&omega;)');
define('MODULE_SYSTEM_REQSER_MORE_TABLES_ADD_DESC', '&Epsilon;&iota;&sigma;ά&gamma;&epsilon;&tau;&epsilon; &epsilon;&delta;ώ &pi;&epsilon;&rho;&alpha;&iota;&tau;έ&rho;&omega; &pi;ί&nu;&alpha;&kappa;&epsilon;&sigmaf; &beta;ά&sigma;&eta;&sigmaf; &delta;&epsilon;&delta;&omicron;&mu;έ&nu;&omega;&nu; &pi;&omicron;&upsilon; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &mu;&epsilon;&tau;&alpha;&phi;&rho;&alpha;&sigma;&tau;&omicron;ύ&nu;, &chi;&omega;&rho;&iota;&sigma;&mu;έ&nu;&omicron;&iota; &mu;&epsilon; &kappa;ό&mu;&mu;&alpha;&tau;&alpha;.<br />(&Gamma;&iota;&alpha; &epsilon;&pi;&epsilon;&kappa;&tau;ά&sigma;&epsilon;&iota;&sigmaf; &mu;&epsilon; &nu;έ&omicron;&upsilon;&sigmaf; "&mu;&eta; &tau;&rho;&omicron;&pi;&omicron;&pi;&omicron;&iota;&eta;&mu;έ&nu;&omicron;&upsilon;&sigmaf; &tau;&upsilon;&pi;&omicron;&pi;&omicron;&iota;&eta;&mu;έ&nu;&omicron;&upsilon;&sigmaf;" &pi;ί&nu;&alpha;&kappa;&epsilon;&sigmaf;)');
define('MODULE_SYSTEM_REQSER_LESS_TABLES_TITLE', '&Epsilon;&xi;&alpha;ί&rho;&epsilon;&sigma;&eta; &pi;&iota;&nu;ά&kappa;&omega;&nu;');
define('MODULE_SYSTEM_REQSER_LESS_TABLES_DESC', '&Epsilon;&iota;&sigma;ά&gamma;&epsilon;&tau;&epsilon; &epsilon;&delta;ώ &tau;&omicron;&upsilon;&sigmaf; &pi;ί&nu;&alpha;&kappa;&epsilon;&sigmaf; &pi;&omicron;&upsilon; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &epsilon;&xi;&alpha;&iota;&rho;&epsilon;&theta;&omicron;ύ&nu; &alpha;&pi;ό &tau;&iota;&sigmaf; &mu;&epsilon;&tau;&alpha;&phi;&rho;ά&sigma;&epsilon;&iota;&sigmaf;, &chi;&omega;&rho;&iota;&sigma;&mu;έ&nu;&omicron;&iota; &mu;&epsilon; &kappa;ό&mu;&mu;&alpha;.<br />(&Alpha;&pi;&alpha;&rho;&alpha;ί&tau;&eta;&tau;&omicron; &mu;ό&nu;&omicron; &alpha;&nu; έ&chi;&omicron;&upsilon;&nu; &epsilon;&pi;&iota;&lambda;&epsilon;&gamma;&epsilon;ί ό&lambda;&omicron;&iota; &omicron;&iota; &tau;&upsilon;&pi;&omicron;&pi;&omicron;&iota;&eta;&mu;έ&nu;&omicron;&iota; &pi;ί&nu;&alpha;&kappa;&epsilon;&sigmaf; &pi;&alpha;&rho;&alpha;&pi;ά&nu;&omega; &kappa;&alpha;&iota; &kappa;ά&pi;&omicron;&iota;&omicron;&iota; &alpha;&pi;ό &alpha;&upsilon;&tau;&omicron;ύ&sigmaf; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &epsilon;&xi;&alpha;&iota;&rho;&epsilon;&theta;&omicron;ύ&nu;).');
define('MODULE_SYSTEM_REQSER_FROM_WHICH_LANG_TITLE', '&Mu;&epsilon;&tau;ά&phi;&rho;&alpha;&sigma;&eta; &alpha;&pi;ό &pi;&omicron;&iota;&alpha; &gamma;&lambda;ώ&sigma;&sigma;&alpha;;');
define('MODULE_SYSTEM_REQSER_FROM_WHICH_LANG_DESC', '&Alpha;&pi;ό &pi;&omicron;&iota;&alpha; &gamma;&lambda;ώ&sigma;&sigma;&alpha; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &gamma;ί&nu;&epsilon;&iota; &eta; &mu;&epsilon;&tau;ά&phi;&rho;&alpha;&sigma;&eta;;');
define('MODULE_SYSTEM_REQSER_INTO_WHICH_LANGS_TITLE', '&Sigma;&epsilon; &pi;&omicron;&iota;&epsilon;&sigmaf; &gamma;&lambda;ώ&sigma;&sigma;&epsilon;&sigmaf; &mu;&pi;&omicron;&rho;ώ &nu;&alpha; &mu;&epsilon;&tau;&alpha;&phi;&rho;ά&sigma;&omega;; ' . draw_tooltip('&Mu;&pi;&omicron;&rho;&epsilon;ί&tau;&epsilon; &nu;&alpha; &pi;&rho;&omicron;&sigma;&theta;έ&sigma;&epsilon;&tau;&epsilon; &epsilon;&pi;&iota;&pi;&lambda;έ&omicron;&nu; &gamma;&lambda;ώ&sigma;&sigma;&epsilon;&sigmaf; &sigma;&tau;&omicron; <i><a href="https://reqser.com/" target="_blank">reqser.com</i></a>.'));
define('MODULE_SYSTEM_REQSER_INTO_WHICH_LANGS_DESC', '&Sigma;&epsilon; &pi;&omicron;&iota;&epsilon;&sigmaf; &gamma;&lambda;ώ&sigma;&sigma;&epsilon;&sigmaf; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &mu;&epsilon;&tau;&alpha;&phi;&rho;&alpha;&sigma;&tau;&epsilon;ί;');
define('MODULE_SYSTEM_REQSER_INTO_ENGLISH_BRITISH_TITLE', '&Tau;&alpha; &alpha;&gamma;&gamma;&lambda;&iota;&kappa;ά &chi;&rho;&eta;&sigma;&iota;&mu;&omicron;&pi;&omicron;&iota;&omicron;ύ&nu;&tau;&alpha;&iota; &omega;&sigmaf; &alpha;&gamma;&gamma;&lambda;&iota;&kappa;ά &tau;&omega;&nu; &Eta;&Pi;&Alpha; &alpha;&pi;ό &pi;&rho;&omicron;&epsilon;&pi;&iota;&lambda;&omicron;&gamma;ή');
define('MODULE_SYSTEM_REQSER_INTO_ENGLISH_BRITISH_DESC', '&Theta;&alpha; &pi;&rho;&omicron;&tau;&iota;&mu;&omicron;ύ&sigma;&alpha;&tau;&epsilon; &tau;&eta; &beta;&rho;&epsilon;&tau;&alpha;&nu;&iota;&kappa;ή &omicron;&rho;&theta;&omicron;&gamma;&rho;&alpha;&phi;ί&alpha;;<br />&Nu;&alpha;&iota; = &beta;&rho;&epsilon;&tau;&alpha;&nu;&iota;&kappa;ή / Ό&chi;&iota; = &Eta;&Pi;&Alpha;');
define('MODULE_SYSTEM_REQSER_ADD_LANGUAGE_ALLOWED_TITLE', '<hr /><h2>&Pi;&epsilon;&rho;&alpha;&iota;&tau;έ&rho;&omega; &rho;&upsilon;&theta;&mu;ί&sigma;&epsilon;&iota;&sigmaf;</h2>&Theta;&alpha; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &epsilon;&pi;&iota;&tau;&rho;&alpha;&pi;&epsilon;ί &eta; &pi;&rho;&omicron;&sigma;&theta;ή&kappa;&eta; &mu;&iota;&alpha;&sigmaf; &nu;έ&alpha;&sigmaf; &gamma;&lambda;ώ&sigma;&sigma;&alpha;&sigmaf; &sigma;&tau;&omicron; <i><a href="https://reqser.com/" target="_blank">reqser.com</i></a> ;');
define('MODULE_SYSTEM_REQSER_ADD_LANGUAGE_ALLOWED_DESC', '&Mu;&epsilon; &alpha;&upsilon;&tau;ή &tau;&eta; &rho;ύ&theta;&mu;&iota;&sigma;&eta; &sigma;&epsilon; "&Nu;&alpha;&iota;", &nu;έ&epsilon;&sigmaf; &gamma;&lambda;ώ&sigma;&sigma;&epsilon;&sigmaf; &mu;&pi;&omicron;&rho;&omicron;ύ&nu; &nu;&alpha; &pi;&rho;&omicron;&sigma;&tau;&epsilon;&theta;&omicron;ύ&nu; &sigma;&tau;&omicron; <i><a href="https://reqser.com/" target="_blank">reqser.com</i></a>.<br />&Mu;&epsilon; &tau;&eta; &rho;ύ&theta;&mu;&iota;&sigma;&eta; "Ό&chi;&iota;", &eta; &gamma;&lambda;ώ&sigma;&sigma;&alpha; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &upsilon;&pi;ά&rho;&chi;&epsilon;&iota; ή&delta;&eta; &sigma;&tau;&omicron; &sigma;ύ&sigma;&tau;&eta;&mu;&alpha; &tau;&omicron;&upsilon; &kappa;&alpha;&tau;&alpha;&sigma;&tau;ή&mu;&alpha;&tau;&omicron;&sigmaf; &kappa;&alpha;&iota; &eta; &gamma;&lambda;ώ&sigma;&sigma;&alpha; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &epsilon;ί&nu;&alpha;&iota; &epsilon;&nu;&epsilon;&rho;&gamma;&omicron;&pi;&omicron;&iota;&eta;&mu;έ&nu;&eta; &sigma;&epsilon; &alpha;&upsilon;&tau;ή &tau;&eta;&nu; &epsilon;&nu;ό&tau;&eta;&tau;&alpha;.<br />&Delta;&eta;&mu;&iota;&omicron;&upsilon;&rho;&gamma;ί&alpha; &gamma;&lambda;ώ&sigma;&sigma;&alpha;&sigmaf; &sigma;&tau;&omicron; &kappa;&alpha;&tau;ά&sigma;&tau;&eta;&mu;&alpha;: <a href="' . DIR_WS_ADMIN . FILENAME_LANGUAGES . '">&amp;raquo &Delta;&eta;&mu;&iota;&omicron;&upsilon;&rho;&gamma;ί&alpha; &gamma;&lambda;ώ&sigma;&sigma;&alpha;&sigmaf; &sigma;&tau;&omicron; &kappa;&alpha;&tau;ά&sigma;&tau;&eta;&mu;&alpha; ?</a> &nbsp;&nbsp;<span class="alrt">!! &Eta; &nu;έ&alpha; &gamma;&lambda;ώ&sigma;&sigma;&alpha; &epsilon;ί&nu;&alpha;&iota; &delta;&iota;&alpha;&theta;έ&sigma;&iota;&mu;&eta; &sigma;&tau;&omicron; &kappa;&alpha;&tau;ά&sigma;&tau;&eta;&mu;&alpha; &mu;ό&nu;&omicron; &mu;&epsilon;&tau;ά &alpha;&pi;ό 24-48 ώ&rho;&epsilon;&sigmaf;. !!</span><br />&Sigma;&tau;&eta; &sigma;&upsilon;&nu;έ&chi;&epsilon;&iota;&alpha;, &sigma;&eta;&mu;&epsilon;&iota;ώ&sigma;&tau;&epsilon; &epsilon;&delta;ώ &omega;&sigmaf; &gamma;&lambda;ώ&sigma;&sigma;&alpha; &pi;&rho;&omicron;&sigmaf; &mu;&epsilon;&tau;ά&phi;&rho;&alpha;&sigma;&eta;');
define('MODULE_SYSTEM_REQSER_LANGUAGE_FILES_TITLE', '&Mu;&epsilon;&tau;ά&phi;&rho;&alpha;&sigma;&eta; &gamma;&lambda;&omega;&sigma;&sigma;&iota;&kappa;ώ&nu; &alpha;&rho;&chi;&epsilon;ί&omega;&nu; &sigma;&tau;&omicron;&nu; &delta;&iota;&alpha;&kappa;&omicron;&mu;&iota;&sigma;&tau;ή;' . draw_tooltip('Ό&lambda;&alpha; &tau;&alpha; &alpha;&rho;&chi;&epsilon;ί&alpha; &sigma;&tau;&omicron;&nu; &delta;&iota;&alpha;&kappa;&omicron;&mu;&iota;&sigma;&tau;ή &alpha;&nu;&alpha;&zeta;&eta;&tau;&omicron;ύ&nu;&tau;&alpha;&iota; &kappa;&alpha;&iota; &mu;&epsilon;&tau;&alpha;&phi;&rho;ά&zeta;&omicron;&nu;&tau;&alpha;&iota;</br>&Alpha;&upsilon;&tau;ό &iota;&sigma;&chi;ύ&epsilon;&iota; &epsilon;&pi;ί&sigma;&eta;&sigmaf; &gamma;&iota;&alpha; &tau;&alpha; &gamma;&lambda;&omega;&sigma;&sigma;&iota;&kappa;ά &alpha;&rho;&chi;&epsilon;ί&alpha; &tau;&omega;&nu; &epsilon;&nu;&omicron;&tau;ή&tau;&omega;&nu; &kappa;&alpha;&iota; &tau;&omega;&nu; &epsilon;&pi;&epsilon;&kappa;&tau;ά&sigma;&epsilon;&omega;&nu;. Ό&lambda;&alpha; &tau;&alpha; &alpha;&rho;&chi;&epsilon;ί&alpha; &gamma;&lambda;&omega;&sigma;&sigma;ώ&nu; &alpha;&nu;&alpha;&gamma;&epsilon;&nu;&nu;ώ&nu;&tau;&alpha;&iota;, &sigma;&upsilon;&mu;&pi;&epsilon;&rho;&iota;&lambda;&alpha;&mu;&beta;&alpha;&nu;&omicron;&mu;έ&nu;&omega;&nu; &tau;&omega;&nu; &upsilon;&phi;&iota;&sigma;&tau;ά&mu;&epsilon;&nu;&omega;&nu; &gamma;&lambda;&omega;&sigma;&sigma;ώ&nu;.<br />&Alpha;&pi;ό &pi;&rho;&omicron;&epsilon;&pi;&iota;&lambda;&omicron;&gamma;ή, &tau;&alpha; &upsilon;&pi;ά&rho;&chi;&omicron;&nu;&tau;&alpha; &xi;&epsilon;&nu;ό&gamma;&lambda;&omega;&sigma;&sigma;&alpha; &kappa;&epsilon;ί&mu;&epsilon;&nu;&alpha; &sigma;&tau;&omicron; Reqser &upsilon;&iota;&omicron;&theta;&epsilon;&tau;&omicron;ύ&nu;&tau;&alpha;&iota; &kappa;&alpha;&iota; &delta;&epsilon;&nu; &mu;&epsilon;&tau;&alpha;&phi;&rho;ά&zeta;&omicron;&nu;&tau;&alpha;&iota; &epsilon;&kappa; &nu;έ&omicron;&upsilon;, &alpha;&lambda;&lambda;ά &alpha;&upsilon;&tau;ό &mu;&pi;&omicron;&rho;&epsilon;ί &nu;&alpha; &alpha;&lambda;&lambda;ά&xi;&epsilon;&iota; &sigma;&tau;&iota;&sigmaf; &rho;&upsilon;&theta;&mu;ί&sigma;&epsilon;&iota;&sigmaf; &tau;&omicron;&upsilon; Reqser.'));
define('MODULE_SYSTEM_REQSER_LANGUAGE_FILES_DESC', '&Chi;&omega;&rho;ί&sigmaf; &alpha;&rho;&chi;&epsilon;ί&alpha; &gamma;&lambda;ώ&sigma;&sigma;&alpha;&sigmaf;, &kappa;&alpha;&mu;ί&alpha; &xi;έ&nu;&eta; &gamma;&lambda;ώ&sigma;&sigma;&alpha; &delta;&epsilon;&nu; &lambda;&epsilon;&iota;&tau;&omicron;&upsilon;&rho;&gamma;&epsilon;ί &sigma;&tau;&omicron; &kappa;&alpha;&tau;ά&sigma;&tau;&eta;&mu;&alpha; &kappa;&alpha;&iota; &upsilon;&pi;ά&rho;&chi;&epsilon;&iota; &mu;&iota;&alpha; "&lambda;&epsilon;&upsilon;&kappa;ή" &sigma;&epsilon;&lambda;ί&delta;&alpha;!');
define('MODULE_SYSTEM_REQSER_LANGUAGE_FILES_SETTING_TITLE', '&Alpha;&upsilon;&tau;ό&mu;&alpha;&tau;&eta; &mu;&epsilon;&tau;&alpha;&phi;&omicron;&rho;ά &alpha;&rho;&chi;&epsilon;ί&omega;&nu; &gamma;&lambda;ώ&sigma;&sigma;&alpha;&sigmaf;;');
define('MODULE_SYSTEM_REQSER_LANGUAGE_FILES_SETTING_DESC', '&Theta;&alpha; &pi;&rho;έ&pi;&epsilon;&iota; &tau;&alpha; &mu;&epsilon;&tau;&alpha;&phi;&rho;&alpha;&sigma;&mu;έ&nu;&alpha; &gamma;&lambda;&omega;&sigma;&sigma;&iota;&kappa;ά &alpha;&rho;&chi;&epsilon;ί&alpha; &nu;&alpha; &mu;&epsilon;&tau;&alpha;&phi;έ&rho;&omicron;&nu;&tau;&alpha;&iota; &alpha;&upsilon;&tau;ό&mu;&alpha;&tau;&alpha; &sigma;&tau;&omicron; &kappa;&alpha;&tau;ά&sigma;&tau;&eta;&mu;ά &sigma;&alpha;&sigmaf; ή &theta;&alpha; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &epsilon;&pi;&iota;&lambda;έ&gamma;&epsilon;&tau;&epsilon; &kappa;ά&theta;&epsilon; &gamma;&lambda;&omega;&sigma;&sigma;&iota;&kappa;ό &alpha;&rho;&chi;&epsilon;ί&omicron; &chi;&epsilon;&iota;&rho;&omicron;&kappa;ί&nu;&eta;&tau;&alpha; &sigma;&tau;&omicron; Reqser;<br />&Nu;&alpha;&iota; = &alpha;&upsilon;&tau;ό&mu;&alpha;&tau;&eta; &mu;&epsilon;&tau;&alpha;&phi;&omicron;&rho;ά &tau;&omega;&nu; &gamma;&lambda;&omega;&sigma;&sigma;&iota;&kappa;ώ&nu; &alpha;&rho;&chi;&epsilon;ί&omega;&nu; / Ό&chi;&iota; = &chi;&epsilon;&iota;&rho;&omicron;&kappa;ί&nu;&eta;&tau;&eta; &mu;&epsilon;&tau;&alpha;&phi;&omicron;&rho;ά');
define('MODULE_SYSTEM_REQSER_PROTOCOL_ACC_TITLE', '<hr /><h2>&Alpha;&sigma;&phi;ά&lambda;&epsilon;&iota;&alpha;</h2>&Kappa;&alpha;&tau;&alpha;&gamma;&rho;&alpha;&phi;ή &pi;&rho;&omicron;&sigma;&beta;ά&sigma;&epsilon;&omega;&nu; API;');
define('MODULE_SYSTEM_REQSER_PROTOCOL_ACC_DESC', '&Pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &kappa;&alpha;&tau;&alpha;&gamma;&rho;ά&phi;&omicron;&nu;&tau;&alpha;&iota; &omicron;&iota; &pi;&rho;&omicron;&sigma;&beta;ά&sigma;&epsilon;&iota;&sigmaf; API;<br />(&Tau;&alpha; &alpha;&rho;&chi;&epsilon;ί&alpha; &kappa;&alpha;&tau;&alpha;&gamma;&rho;&alpha;&phi;ή&sigmaf; &beta;&rho;ί&sigma;&kappa;&omicron;&nu;&tau;&alpha;&iota; &sigma;&tau;&omicron; <i>/api/reqser/logs/</i> ).');
define('MODULE_SYSTEM_REQSER_BROWSER_TEST_TITLE', '&Delta;&omicron;&kappa;&iota;&mu;ή &sigma;&tau;&omicron; &pi;&rho;ό&gamma;&rho;&alpha;&mu;&mu;&alpha; &pi;&epsilon;&rho;&iota;ή&gamma;&eta;&sigma;&eta;&sigmaf; ?');
define('MODULE_SYSTEM_REQSER_BROWSER_TEST_DESC', '&Delta;&omicron;&kappa;&iota;&mu;ή &sigma;&tau;&omicron; &pi;&rho;ό&gamma;&rho;&alpha;&mu;&mu;&alpha; &pi;&epsilon;&rho;&iota;ή&gamma;&eta;&sigma;&eta;&sigmaf; &chi;&omega;&rho;ί&sigmaf; &alpha;&pi;&omicron;&sigma;&tau;&omicron;&lambda;ή &kappa;&epsilon;&phi;&alpha;&lambda;ί&delta;&omega;&nu;;<br /><span class="alrt">!!! &Pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &alpha;&pi;&epsilon;&nu;&epsilon;&rho;&gamma;&omicron;&pi;&omicron;&iota;&eta;&theta;&epsilon;ί &sigma;&tau;&eta; &zeta;&omega;&nu;&tau;&alpha;&nu;ή &lambda;&epsilon;&iota;&tau;&omicron;&upsilon;&rho;&gamma;ί&alpha; &tau;&omicron;&upsilon; API !!!</span>');
define('MODULE_SYSTEM_REQSER_API_KEY_WRONG_ERR', '&Tau;&omicron; "&kappa;&lambda;&epsilon;&iota;&delta;ί API Reqser" &pi;&omicron;&upsilon; &epsilon;ί&nu;&alpha;&iota; &alpha;&pi;&omicron;&theta;&eta;&kappa;&epsilon;&upsilon;&mu;έ&nu;&omicron; &epsilon;&delta;ώ &sigma;&tau;&eta;&nu; &epsilon;&nu;ό&tau;&eta;&tau;&alpha; &delta;&epsilon;&nu; &tau;&alpha;&iota;&rho;&iota;ά&zeta;&epsilon;&iota; &mu;&epsilon; &alpha;&upsilon;&tau;ό &pi;&omicron;&upsilon; &epsilon;ί&nu;&alpha;&iota; &alpha;&pi;&omicron;&theta;&eta;&kappa;&epsilon;&upsilon;&mu;έ&nu;&omicron; &sigma;&tau;&omicron; <i>reqser.com</i>.<br />&Pi;&alpha;&rho;&alpha;&kappa;&alpha;&lambda;&omicron;ύ&mu;&epsilon; &sigma;&upsilon;&nu;&delta;&epsilon;&theta;&epsilon;ί&tau;&epsilon; &sigma;&tau;&omicron; <i>reqser</i>.com &kappa;&alpha;&iota; &epsilon;&lambda;έ&gamma;&xi;&tau;&epsilon; &tau;&omicron; &kappa;&lambda;&epsilon;&iota;&delta;ί API ή, &epsilon;ά&nu; &epsilon;ί&nu;&alpha;&iota; &alpha;&pi;&alpha;&rho;&alpha;ί&tau;&eta;&tau;&omicron;, &alpha;&nu;&alpha;&kappa;&tau;ή&sigma;&tau;&epsilon; &tau;&omicron; &xi;&alpha;&nu;ά &kappa;&alpha;&iota; &alpha;&pi;&omicron;&theta;&eta;&kappa;&epsilon;ύ&sigma;&tau;&epsilon; &tau;&omicron; &epsilon;&delta;ώ.');
define('MODULE_SYSTEM_REQSER_API_KEY_SUCCESS', '&Tau;&omicron; &kappa;&lambda;&epsilon;&iota;&delta;ί API &alpha;&pi;&omicron;&theta;&eta;&kappa;&epsilon;ύ&tau;&eta;&kappa;&epsilon; &epsilon;&pi;&iota;&tau;&upsilon;&chi;ώ&sigmaf;');
define('MODULE_SYSTEM_REQSER_API_KEY_EMPTY_ERR', '&Delta;&epsilon;&nu; έ&chi;&epsilon;&iota; &epsilon;&iota;&sigma;&alpha;&chi;&theta;&epsilon;ί &kappa;&lambda;&epsilon;&iota;&delta;ί API! &Sigma;&upsilon;&nu;&delta;&epsilon;&theta;&epsilon;ί&tau;&epsilon; &sigma;&tau;&omicron; <i>reqser.</i> com &kappa;&alpha;&iota; &lambda;ά&beta;&epsilon;&tau;&epsilon; &tau;&omicron; &kappa;&lambda;&epsilon;&iota;&delta;ί API &gamma;&iota;&alpha; &alpha;&upsilon;&tau;ό&nu; &tau;&omicron;&nu; &iota;&sigma;&tau;ό&tau;&omicron;&pi;&omicron; &kappa;&alpha;&iota; &alpha;&pi;&omicron;&theta;&eta;&kappa;&epsilon;ύ&sigma;&tau;&epsilon; &tau;&omicron; &epsilon;&delta;ώ &sigma;&tau;&eta;&nu; &epsilon;&nu;ό&tau;&eta;&tau;&alpha;.');
define('MODULE_SYSTEM_REQSER_CURL_ERR', 'cURL ERROR:<br />%s');
define('MODULE_SYSTEM_REQSER_INTO_LANGS_EMPTY_ERR', '&Delta;&epsilon;&nu; έ&chi;&epsilon;&iota; &epsilon;&pi;&iota;&lambda;&epsilon;&gamma;&epsilon;ί &kappa;ά&pi;&omicron;&iota;&alpha; &gamma;&lambda;ώ&sigma;&sigma;&alpha; &pi;&rho;&omicron;&sigmaf; &mu;&epsilon;&tau;ά&phi;&rho;&alpha;&sigma;&eta; !');
define('MODULE_SYSTEM_REQSER_IWL_IN_FWL_ERR', '&Tau;&omicron; "&Mu;&epsilon;&tau;ά&phi;&rho;&alpha;&sigma;&eta; &sigma;&epsilon; &pi;&omicron;&iota;&epsilon;&sigmaf; &gamma;&lambda;ώ&sigma;&sigma;&epsilon;&sigmaf;;" &delta;&epsilon;&nu; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &pi;&epsilon;&rho;&iota;έ&chi;&epsilon;&iota; &gamma;&lambda;ώ&sigma;&sigma;&alpha; &pi;&omicron;&upsilon; έ&chi;&epsilon;&iota; &epsilon;&pi;&iota;&lambda;&epsilon;&gamma;&epsilon;ί &sigma;&tau;&omicron; "&Mu;&epsilon;&tau;ά&phi;&rho;&alpha;&sigma;&eta; &alpha;&pi;ό &pi;&omicron;&iota;&alpha; &gamma;&lambda;ώ&sigma;&sigma;&alpha;;".');
define('MODULE_SYSTEM_REQSER_ADMIN_MESSAGE', '&Eta; &epsilon;&nu;ό&tau;&eta;&tau;&alpha; Reqser.com DeepL &theta;&alpha; &mu;&epsilon;&tau;&alpha;&phi;&rho;ά&sigma;&epsilon;&iota; &alpha;&upsilon;&tau;ό&mu;&alpha;&tau;&alpha; ό&lambda;&epsilon;&sigmaf; &tau;&iota;&sigmaf; &xi;έ&nu;&epsilon;&sigmaf; &gamma;&lambda;ώ&sigma;&sigma;&epsilon;&sigmaf; &pi;&omicron;&upsilon; έ&chi;&omicron;&upsilon;&nu; &epsilon;&nu;&epsilon;&rho;&gamma;&omicron;&pi;&omicron;&iota;&eta;&theta;&epsilon;ί &sigma;&tau;&eta;&nu; &epsilon;&nu;ό&tau;&eta;&tau;&alpha; &gamma;&iota;&alpha; &alpha;&upsilon;&tau;ό &tau;&omicron; &pi;&rho;&omicron;ϊό&nu; &mu;&epsilon;&tau;ά &tau;&eta;&nu; &alpha;&pi;&omicron;&theta;ή&kappa;&epsilon;&upsilon;&sigma;&eta;.');
define('MODULE_SYSTEM_REQSER_ADMIN_MISSING_API_KEY', '&Eta; &epsilon;&nu;ό&tau;&eta;&tau;&alpha; Deepl Translator &tau;&omicron;&upsilon; Reqser.com &delta;&epsilon;&nu; έ&chi;&epsilon;&iota; &kappa;&lambda;&epsilon;&iota;&delta;ί API, &pi;&alpha;&rho;&alpha;&kappa;&alpha;&lambda;ώ &epsilon;&iota;&sigma;ά&gamma;&epsilon;&tau;&epsilon; έ&nu;&alpha; &kappa;&lambda;&epsilon;&iota;&delta;ί API');
define('MODULE_SYSTEM_REQSER_ADMIN_INSTALLED_NOT_ACTIVATED', 'Reqser.com &Eta; &epsilon;&nu;ό&tau;&eta;&tau;&alpha; Deepl Translator &delta;&epsilon;&nu; &epsilon;ί&nu;&alpha;&iota; &epsilon;&nu;&epsilon;&rho;&gamma;&omicron;&pi;&omicron;&iota;&eta;&mu;έ&nu;&eta;, &pi;&alpha;&rho;&alpha;&kappa;&alpha;&lambda;&omicron;ύ&mu;&epsilon; &epsilon;&nu;&epsilon;&rho;&gamma;&omicron;&pi;&omicron;&iota;ή&sigma;&tau;&epsilon; &tau;&eta;&nu; &epsilon;&nu;ό&tau;&eta;&tau;&alpha; &sigma;&tau;&omicron; Module->System Module');
define('MODULE_SYSTEM_REQSER_ADMIN_MESSAGE_MISSING_CONNECTION', '&Eta; &epsilon;&nu;ό&tau;&eta;&tau;&alpha; Deepl Translator &tau;&omicron;&upsilon; Reqser.com &delta;&epsilon;&nu; έ&chi;&epsilon;&iota; &kappa;&alpha;&mu;ί&alpha; &sigma;ύ&nu;&delta;&epsilon;&sigma;&eta;!');